import { chromium } from 'playwright';
const browser = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, hasTouch: true, isMobile: true });
page.on('pageerror', (e) => console.log('pageerror:', e.message));
await page.goto('http://localhost:5173/'); await page.waitForTimeout(2500);
await page.fill('.intro input', 'Baptiste'); await page.click('.intro .btn'); await page.waitForTimeout(800);
await page.evaluate(() => window.ragots.openDialog('gaston')); await page.waitForTimeout(2000);
await page.click('text=🛒 Acheter'); await page.waitForTimeout(500);
await page.screenshot({ path: 'shots/shop-1.png' });
await page.locator('.item-row').filter({ hasText: 'Banc' }).locator('button').click();
await page.fill('.inputrow input', 'Allez Gaston, avec ta moustache magnifique, tu me le fais à 250 ?');
await page.click('.inputrow .send'); await page.waitForTimeout(6000);
await page.screenshot({ path: 'shots/shop-2.png' });
await page.click('text=Topé !'); await page.waitForTimeout(1500);
await page.evaluate(() => window.ragots.closeDialog());
await page.click('text=Déco'); await page.waitForTimeout(500);
const st = await page.evaluate(() => window.ragots.store.state.player.inventory.map((s) => s.itemId));
console.log('inv', st);
await page.evaluate(() => { const w = window.ragots.world; w.onTap({ kind: 'slot', id: 'placette' }); });
await page.waitForTimeout(500);
await page.screenshot({ path: 'shots/shop-3.png' });
await page.locator('.item-row button', { hasText: 'Poser' }).first().click().catch((e) => console.log('no poser', e.message));
await page.waitForTimeout(1500);
await page.screenshot({ path: 'shots/shop-4.png' });
await browser.close();
